export const TOGGLE_NEW_MENU = 'TOGGLE_NEW_MENU';
export const TOGGLE_LOGIN_FORM = 'TOGGLE_LOGIN_FORM';
export const SHOW_NEW_CONTACT_MODAL = 'SHOW_NEW_CONTACT_MODAL';
export const HIDE_NEW_CONTACT_MODAL = 'HIDE_NEW_CONTACT_MODAL';
